defaults: &defaults
  InbloomPortalUrl: 'https://portal.sandbox.inbloom.org/portal'
  InbloomAPIUrl: 'https://api.sandbox.slcedu.org'

development:
  <<: *defaults
  mock_in_bloom: true

staging:
  <<: *defaults

production:
  <<: *defaults